services:
  kodbox:
    image: kodcloud/kodbox:latest
    container_name: kodbox
    restart: always
    ports:
      - "807:80"       # 网页访问端口：http://路由器IP:807
    volumes:
      - ./kodbox-data:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    privileged: true